#!/usr/bin/env python3
"""Renders analysis/feature_analysis.json into analysis/feature_analysis_report.html.
Purely mechanical (like parse_md_to_csv.py / build_site.py) — free to re-run, no API calls.
The JSON itself is the authored analysis output and is not regenerated by this script;
re-run scripts/compute_feature_stats.py first if you want to refresh the underlying numbers,
then update feature_analysis.json by hand before re-rendering."""

import html as htmllib
import json
import os
import re

import base64

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_PATH = os.path.join(REPO_ROOT, "analysis", "feature_analysis.json")
OUT_PATH = os.path.join(REPO_ROOT, "analysis", "feature_analysis_report.html")
LOGO_PATH = os.path.join(REPO_ROOT, "docs", "assets", "reuse-logo.png")


def logo_data_uri():
    with open(LOGO_PATH, "rb") as f:
        b64 = base64.b64encode(f.read()).decode("ascii")
    return f"data:image/png;base64,{b64}"


def esc(s):
    return htmllib.escape(str(s), quote=False)


def prevalence_class(p):
    p = p.lower()
    if "high" in p and "rising" not in p:
        return "prev-high"
    if "rising" in p or "medium" in p:
        return "prev-medium"
    if "low" in p:
        return "prev-low"
    return "prev-medium"


def render_features(features):
    blocks = []
    for feat in features:
        ex_html = ""
        if feat["examples"]:
            ex_items = ", ".join(esc(e) for e in feat["examples"])
            ex_html = f'<p class="examples"><span class="examples-label">Examples</span> {ex_items}</p>'
        blocks.append(f"""
    <article class="feature">
      <div class="feature-head">
        <h3>{esc(feat['feature'])}</h3>
        <span class="pill {prevalence_class(feat['prevalence'])}">{esc(feat['prevalence'])}</span>
      </div>
      <p class="feature-desc">{esc(feat['description'])}</p>
      {ex_html}
    </article>
    """)
    return "\n".join(blocks)


def prose_section(title, number, text, id_):
    parts = re.split(r"(?=\d\)\s)", text)
    parts = [p.strip() for p in parts if p.strip()]
    if len(parts) > 1:
        cleaned = [re.sub(r"^\d\)\s*", "", p) for p in parts]
        items = "".join(f"<li>{esc(c)}</li>" for c in cleaned)
        body = f'<ol class="reco-list">{items}</ol>'
    else:
        body = f"<p>{esc(text)}</p>"
    return f"""
    <section class="report-section" id="{id_}">
      <div class="section-head">
        <span class="section-num">{number}</span>
        <h2>{title}</h2>
      </div>
      {body}
    </section>
    """


CSS = """
:root {
  --paper: #ffffff; --paper-raised: #f5fafd; --ink: #282626; --muted: #66655f;
  --accent: #006699; --accent-bright: #57c7ff; --accent-soft: #e8f7ff; --line: #dfe3e6;
  --tier-high: #1f6b52; --tier-high-bg: #dcece4;
  --tier-medium: #8a6413; --tier-medium-bg: #ede2c4;
  --tier-low: #8a5236; --tier-low-bg: #ecdfd6;
  --serif: Iowan Old Style, "Palatino Linotype", Palatino, Georgia, "Noto Serif", serif;
  --sans: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  --mono: ui-monospace, SFMono-Regular, "SF Mono", "Cascadia Code", "Roboto Mono", Consolas, monospace;
}
@media (prefers-color-scheme: dark) {
  :root {
    --paper: #000000; --paper-raised: #111214; --ink: #f0f1f2; --muted: #9a9d9f;
    --accent: #57c7ff; --accent-bright: #57c7ff; --accent-soft: #0d2733; --line: #26292c;
    --tier-high: #7fd9ac; --tier-high-bg: #1e3a2c;
    --tier-medium: #d9b969; --tier-medium-bg: #3a3018;
    --tier-low: #d99a76; --tier-low-bg: #3a2a1f;
  }
}
:root[data-theme="dark"] {
  --paper: #000000; --paper-raised: #111214; --ink: #f0f1f2; --muted: #9a9d9f;
  --accent: #57c7ff; --accent-bright: #57c7ff; --accent-soft: #0d2733; --line: #26292c;
  --tier-high: #7fd9ac; --tier-high-bg: #1e3a2c;
  --tier-medium: #d9b969; --tier-medium-bg: #3a3018;
  --tier-low: #d99a76; --tier-low-bg: #3a2a1f;
}
:root[data-theme="light"] {
  --paper: #ffffff; --paper-raised: #f5fafd; --ink: #282626; --muted: #66655f;
  --accent: #006699; --accent-bright: #57c7ff; --accent-soft: #e8f7ff; --line: #dfe3e6;
  --tier-high: #1f6b52; --tier-high-bg: #dcece4;
  --tier-medium: #8a6413; --tier-medium-bg: #ede2c4;
  --tier-low: #8a5236; --tier-low-bg: #ecdfd6;
}
* { box-sizing: border-box; }
html { background: var(--paper); }
body { margin: 0; background: var(--paper); color: var(--ink); font-family: var(--sans); font-size: 17px; line-height: 1.65; }
.wrap { max-width: 760px; margin: 0 auto; padding: 3.5rem 1.5rem 6rem; }
.masthead { border-bottom: 2px solid var(--ink); padding-bottom: 1.6rem; margin-bottom: 2rem; }
.masthead-logo { height: 30px; width: auto; margin-bottom: 1.1rem; display: block; }
.eyebrow { font-family: var(--mono); font-size: 0.72rem; letter-spacing: 0.12em; text-transform: uppercase; color: var(--accent); margin: 0 0 0.7rem; }
h1 { font-family: var(--serif); font-weight: 600; font-size: 2.3rem; line-height: 1.15; margin: 0 0 0.6rem; text-wrap: balance; letter-spacing: -0.01em; }
.subtitle { color: var(--muted); font-size: 1.02rem; max-width: 62ch; margin: 0; }
.methodology { font-size: 0.88rem; color: var(--muted); border-left: 2px solid var(--line); padding: 0.15rem 0 0.15rem 0.9rem; margin: 1.3rem 0 0; font-style: italic; }
.ledger { display: flex; flex-wrap: wrap; gap: 0; margin: 1.8rem 0 2.6rem; border-top: 1px solid var(--line); border-bottom: 1px solid var(--line); }
.ledger-item { flex: 1 1 140px; padding: 0.9rem 1.1rem; border-right: 1px solid var(--line); }
.ledger-item:last-child { border-right: none; }
.ledger-num { font-family: var(--mono); font-variant-numeric: tabular-nums; font-size: 1.5rem; font-weight: 600; color: var(--accent); }
.ledger-label { font-size: 0.76rem; color: var(--muted); text-transform: uppercase; letter-spacing: 0.05em; margin-top: 0.15rem; }
.section-head { display: flex; align-items: baseline; gap: 0.7rem; margin: 0 0 1.1rem; }
.section-num { font-family: var(--mono); font-size: 0.85rem; color: var(--muted); }
h2 { font-family: var(--serif); font-weight: 600; font-size: 1.5rem; margin: 0; padding-bottom: 0.5rem; border-bottom: 1px solid var(--line); flex: 1; text-wrap: balance; }
.report-section { margin-bottom: 3rem; }
.report-section > p { max-width: 68ch; }
.feature { padding: 1.1rem 0; border-bottom: 1px solid var(--line); }
.feature:first-of-type { border-top: 1px solid var(--line); }
.feature-head { display: flex; align-items: baseline; justify-content: space-between; gap: 1rem; margin-bottom: 0.45rem; }
.feature-head h3 { font-family: var(--serif); font-weight: 600; font-size: 1.12rem; margin: 0; text-wrap: balance; }
.pill { font-family: var(--mono); font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.04em; padding: 0.2rem 0.55rem; border-radius: 3px; white-space: nowrap; flex-shrink: 0; }
.prev-high { background: var(--tier-high-bg); color: var(--tier-high); }
.prev-medium { background: var(--tier-medium-bg); color: var(--tier-medium); }
.prev-low { background: var(--tier-low-bg); color: var(--tier-low); }
.feature-desc { margin: 0 0 0.5rem; max-width: 68ch; }
.examples { font-size: 0.88rem; color: var(--muted); margin: 0; max-width: 68ch; }
.examples-label { font-family: var(--mono); font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.05em; color: var(--accent); margin-right: 0.4rem; }
.reco-list { margin: 0; padding-left: 1.3rem; max-width: 68ch; }
.reco-list li { margin-bottom: 0.9rem; padding-left: 0.3rem; }
.reco-list li::marker { font-family: var(--mono); color: var(--accent); font-weight: 600; }
footer { margin-top: 3.5rem; padding-top: 1.3rem; border-top: 2px solid var(--ink); font-size: 0.82rem; color: var(--muted); display: flex; justify-content: space-between; flex-wrap: wrap; gap: 0.5rem; }
footer .confidential { font-family: var(--mono); text-transform: uppercase; letter-spacing: 0.06em; }
@media (max-width: 600px) {
  .wrap { padding: 2rem 1.1rem 4rem; }
  h1 { font-size: 1.8rem; }
  .ledger-item { flex: 1 1 45%; border-bottom: 1px solid var(--line); }
  .feature-head { flex-direction: column; align-items: flex-start; gap: 0.35rem; }
}
"""

PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Feature Analysis — REUSE &amp; Refill Organisations</title>
<style>{css}</style>
</head>
<body>
<div class="wrap">
  <div class="masthead">
    <img class="masthead-logo" src="{logo_uri}" alt="REUSE Foundation">
    <p class="eyebrow">REUSE Foundation — Internal Analysis</p>
    <h1>Feature Analysis: Reuse &amp; Refill Organisations</h1>
    <p class="subtitle">Common features, patterns, and success factors across the REUSE Foundation Knowledge Library — computed directly from the full researched dataset, not sampled.</p>
    <p class="methodology">{methodology}</p>
  </div>

  <div class="ledger">
    <div class="ledger-item"><div class="ledger-num">708</div><div class="ledger-label">Organisations analysed</div></div>
    <div class="ledger-item"><div class="ledger-num">69</div><div class="ledger-label">Countries represented</div></div>
    <div class="ledger-item"><div class="ledger-num">{n_features}</div><div class="ledger-label">Patterns identified</div></div>
    <div class="ledger-item"><div class="ledger-num">78%</div><div class="ledger-label">Founded since 2010</div></div>
  </div>

  <section class="report-section" id="features">
    <div class="section-head">
      <span class="section-num">01</span>
      <h2>Key common features</h2>
    </div>
    {features_section}
  </section>

  {rest_sections}

  <footer>
    <span>Source: <code>data/REUSE_V5_Master.csv</code>, REUSE-Foundation-Knowledge-Library</span>
    <span class="confidential">Confidential — internal use only</span>
  </footer>
</div>
</body>
</html>
"""


def main():
    with open(JSON_PATH, encoding="utf-8") as f:
        data = json.load(f)

    features_section = render_features(data["key_common_features"])
    rest_sections = "\n".join([
        prose_section("Actionable search criteria", "02", data["actionable_search_criteria"], "search-criteria"),
        prose_section("Success factors", "03", data["success_factors"], "success-factors"),
        prose_section("Potential gaps", "04", data["potential_gaps"], "potential-gaps"),
        prose_section("Recommendations", "05", data["recommendations"], "recommendations"),
    ])

    page = PAGE.format(
        css=CSS,
        logo_uri=logo_data_uri(),
        methodology=esc(data["methodology_note"]),
        n_features=len(data["key_common_features"]),
        features_section=features_section,
        rest_sections=rest_sections,
    )

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(page)
    print(f"Wrote {OUT_PATH} ({len(page)} bytes)")


if __name__ == "__main__":
    main()
